language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t phe0/docker-aws -f Dockerfile.dev .

script:
  - docker run -e CI=true phe0/docker-aws npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-aws"
  env: "DockerAws-env"
  bucket_name: "elasticbeanstalk-us-east-2-747187906338"
  bucket_path: "docker-aws"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
